### ISSUE TITLE
How do I use this with gulp?

### ISSUE THREAD

**Issue by rlam3** [raulghm/Font-Awesome-Stylus#27]
How do I use this with gulp?

**Comment by rlam3** [comment]
I'm getting the following error when using with gulp 


```
(function (exports, require, module, __filename, __dirname) { @import "font-aw
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/stylus/bin/stylus:787:10
    at Array.forEach (native)
    at usePlugins (/usr/local/lib/node_modules/stylus/bin/stylus:784:11)
```
